version: "2"
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /Users/luyang.gai/data/mongo:/data/db
  # node:
  #   build: .
  #   ports:
  #     - "8000:8080"

